apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes-team-cloud.fullname" . }}-config
  labels:
    {{- include "hermes-team-cloud.labels" . | nindent 4 }}
data:
  TEAM_CLOUD_ENVIRONMENT: {{ .Values.config.environment | quote }}
  TEAM_CLOUD_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  TEAM_CLOUD_JWT_ISSUER: {{ .Values.config.jwtIssuer | quote }}
  TEAM_CLOUD_CASDOOR_BASE_URL: {{ .Values.config.casdoorBaseUrl | quote }}
  TEAM_CLOUD_CASDOOR_CLIENT_ID: {{ .Values.config.casdoorClientId | quote }}
  TEAM_CLOUD_SPICEDB_ENDPOINT: {{ .Values.config.spicedbEndpoint | quote }}
  TEAM_CLOUD_MINIO_ENDPOINT: {{ .Values.config.minioEndpoint | quote }}
  TEAM_CLOUD_MINIO_ACCESS_KEY: {{ .Values.config.minioAccessKey | quote }}
  TEAM_CLOUD_BACKUP_MOUNT_PATH: {{ .Values.persistence.backup.mountPath | quote }}

