{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hermes-team-cloud.backupPvcName" . }}
  labels:
    {{- include "hermes-team-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup-storage
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backup.size | quote }}
{{- end }}

