#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

MATRIX="teamDoc/GADoc/artifacts/platform-foundation-smoke-v0.json"
if [[ ! -f "$MATRIX" ]]; then
  echo "Missing smoke matrix: $MATRIX" >&2
  exit 2
fi

scripts/run_tests.sh \
  tests/test_project_metadata.py \
  tests/run_agent/test_memory_provider_init.py \
  tests/gateway/test_api_server_team_headers.py \
  tests/gateway/test_gateway_team_identity_resolver.py \
  tests/team_cloud/test_config_secret_management.py \
  tests/team_cloud/test_skeleton.py \
  tests/team_cloud/test_local_compose_stack.py \
  tests/team_cloud/test_compose_hardening.py \
  tests/team_cloud/test_helm_chart.py \
  tests/team_cloud/test_offline_bundle.py \
  tests/team_cloud/test_postgres_migrations.py \
  tests/team_cloud/test_memory_migrations.py \
  tests/team_cloud/test_memory_query_layer.py \
  tests/team_cloud/test_memory_crud_api.py \
  tests/team_cloud/test_memory_relationships.py \
  tests/team_cloud/test_memory_embedding_worker.py \
  tests/team_cloud/test_memory_extraction_worker.py \
  tests/team_cloud/test_memory_review_api.py \
  tests/team_cloud/test_memory_observations_api.py \
  tests/team_cloud/test_memory_duplicate_conflict_detector.py \
  tests/team_cloud/test_memory_pii_secret_detector.py \
  tests/team_cloud/test_team_memory_provider.py \
  tests/team_cloud/test_team_memory_provider_tools.py \
  tests/team_cloud/test_memory_prefetch_pipeline.py \
  tests/team_cloud/test_memory_performance_baseline.py \
  tests/team_cloud/test_external_identity_resolver.py \
  tests/team_cloud/test_casdoor_oidc.py \
  tests/team_cloud/test_jwt_middleware.py \
  tests/team_cloud/test_casdoor_sync_worker.py \
  tests/team_cloud/test_pat_service_accounts.py \
  tests/team_cloud/test_spicedb_client.py \
  tests/team_cloud/test_spicedb_schema_ci.py \
  tests/team_cloud/test_relationship_outbox.py \
  tests/team_cloud/test_authz_middleware.py \
  tests/team_cloud/test_authz_chaos.py \
  tests/team_cloud/test_admin_org_api.py \
  tests/team_cloud/test_audit_baseline.py \
  tests/team_cloud/test_audit_advanced.py \
  tests/team_cloud/test_usage_quotas.py \
  tests/team_cloud/test_minio_manifest.py \
  tests/team_cloud/test_web_login_shell.py \
  tests/team_cloud/test_web_admin_pages.py \
  tests/team_cloud/test_web_chat_entry.py \
  tests/team_cloud/test_cloud_session_history.py \
  tests/team_cloud/test_sessiondb_import.py \
  tests/team_cloud/test_runtime_event_bridge.py \
  tests/team_cloud/test_isolation_suite.py \
  tests/team_cloud/test_load_test_scripts.py \
  tests/team_cloud/test_security_test_suite.py \
  tests/team_cloud/test_final_security_review.py \
  tests/team_cloud/test_sbom_license_package.py \
  tests/team_cloud/test_install_guide.py \
  tests/team_cloud/test_admin_user_manuals.py \
  tests/team_cloud/test_api_docs_package.py \
  tests/team_cloud/test_runbook_summary.py \
  tests/team_cloud/test_release_notes.py \
  tests/team_cloud/test_ga_signoff.py \
  tests/team_cloud/test_support_playbook.py \
  tests/team_cloud/test_migration_guide.py \
  tests/team_cloud/test_training_material.py \
  tests/team_cloud/test_final_regression.py \
  tests/team_cloud/test_deployment_smoke.py \
  tests/team_cloud/test_legal_compliance_package.py \
  tests/team_cloud/test_post_ga_backlog.py \
  tests/team_cloud/test_release_manual.py \
  tests/team_cloud/test_ga_release_checklist.py \
  tests/team_cloud/test_upgrade_rollback.py \
  tests/team_cloud/test_performance_tuning.py \
  tests/team_cloud/test_pilot_onboarding.py \
  tests/team_cloud/test_pilot_telemetry_review.py \
  tests/team_cloud/test_bug_triage_process.py \
  tests/team_cloud/test_cost_quota_tuning.py \
  tests/team_cloud/test_chaos_drills.py \
  tests/team_cloud/test_beta_docs.py \
  tests/team_cloud/test_beta_exit_report.py \
  tests/team_cloud/test_i18n_accessibility.py \
  tests/team_cloud/test_permission_explorer_minimal.py \
  tests/team_cloud/test_permission_explorer_ga.py \
  tests/team_cloud/test_platform_security_negative.py \
  tests/team_cloud/test_observability_baseline.py \
  tests/team_cloud/test_metrics_dashboard.py \
  tests/team_cloud/test_logs_traces.py \
  tests/team_cloud/test_memory_runtime_docs.py \
  tests/team_cloud/test_tool_risk_taxonomy.py \
  tests/team_cloud/test_team_tool_policy_hook.py \
  tests/team_cloud/test_tool_audit.py \
  tests/team_cloud/test_backup_policy.py \
  tests/team_cloud/test_backup_exporter.py \
  tests/team_cloud/test_backup_storage.py \
  tests/team_cloud/test_backup_restore_drill.py \
  tests/team_cloud/test_platform_backup_restore_drill.py \
  tests/team_cloud/test_restore_preview.py \
  tests/team_cloud/test_restore_execute.py \
  tests/team_cloud/test_org_export.py \
  tests/team_cloud/test_deletion_request.py \
  tests/team_cloud/test_hard_delete_worker.py \
  tests/team_cloud/test_retention_policies.py \
  tests/team_cloud/test_break_glass.py \
  tests/team_cloud/test_data_governance_docs.py \
  tests/team_cloud/test_notifications.py \
  tests/team_cloud/test_admin_ux_final.py \
  tests/team_cloud/test_deployment_docs.py \
  tests/team_cloud/test_platform_foundation_suite.py
